Update Packages-AutoBuild.yml

diff --git a/.github/workflows/Packages-AutoBuild.yml b/.github/workflows/Packages-AutoBuild.yml
--- a/.github/workflows/Packages-AutoBuild.yml
+++ b/.github/workflows/Packages-AutoBuild.yml
@@ -236,7 +236,7 @@ jobs:
               mv -f feeds/packages.b feeds/packages
               [ "$(grep "PKG_BUILD_DEPENDS" package/feeds/kiddin9/$ipk/Makefile)" ] || mv feeds/packages/lang/node feeds/packages/lang/node.b
              fi
-             (make -k package/$ipk/compile -j$(($(nproc)+1)) || make package/$ipk/compile V=s 2>&1 | tee error_$ipk.log | grep -i "Error 2" || rm -rf error_$ipk.log) || true
+             make -k package/$ipk/compile -j$(($(nproc)+1)) || { echo "${{ github.event.action }}" | grep -qv "a-" && make package/$ipk/compile V=s 2>&1 | tee error_$ipk.log | grep -i "Error 2"; } || true
              if [[ $ipk != luci-* ]]; then
               mv -f feeds/packages/lang/node.b feeds/packages/lang/node 2>/dev/null || true
               mv -f feeds/packages feeds/packages.b
