update

diff --git a/.github/workflows/Packages-AutoBuild.yml b/.github/workflows/Packages-AutoBuild.yml
--- a/.github/workflows/Packages-AutoBuild.yml
+++ b/.github/workflows/Packages-AutoBuild.yml
@@ -65,6 +65,7 @@ jobs:
 
     - name: Free disk space
       uses: coder-xiaomo/free-disk-space@main
+      if: contains(github.event.action, 'a-')
       with:
         tool-cache: false
         android: true
@@ -97,52 +98,59 @@ jobs:
     - name: Clone source code
       run: |
         set -v
-        REPO_BRANCH="24.10-SNAPSHOT"
+        REPO_BRANCH="25.12-SNAPSHOT"
         #REPO_BRANCH="$(curl -gs -H 'Content-Type: application/json' \
         #   -H "Authorization: Bearer ${{ secrets.TOKEN_KIDDIN9 }}" \
         #   -X POST -d '{ "query": "query {repository(owner: \"openwrt\", name: \"openwrt\") {refs(refPrefix: \"refs/tags/\", last: 4, orderBy: {field: TAG_COMMIT_DATE, direction: ASC}) {edges {node {name}}}}}"}' https://api.github.com/graphql | jq -r '.data.repository.refs.edges[].node.name' | grep v23 | tail -n 1 | sed -e 's/v//')" || true
         echo "$REPO_BRANCH"
-        if [ ${{matrix.target}} == "mipsel_24kc" ]; then
-            curl -fL -o sdk.tar.zst https://downloads.openwrt.org/releases/$REPO_BRANCH/targets/ramips/mt7621/openwrt-sdk-$REPO_BRANCH-ramips-mt7621_gcc-13.3.0_musl.Linux-x86_64.tar.zst
-        elif [ ${{matrix.target}} == "mips_24kc" ]; then
-            curl -fL -o sdk.tar.zst https://downloads.openwrt.org/releases/$REPO_BRANCH/targets/ath79/nand/openwrt-sdk-$REPO_BRANCH-ath79-nand_gcc-13.3.0_musl.Linux-x86_64.tar.zst
-        elif [[ ${{matrix.target}} == "x86_64" ]]; then
-            curl -fL -o sdk.tar.zst https://downloads.openwrt.org/releases/$REPO_BRANCH/targets/x86/64/openwrt-sdk-$REPO_BRANCH-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst
-        elif [[ ${{matrix.target}} == "i386_pentium4" ]]; then
-            curl -fL -o sdk.tar.zst https://downloads.openwrt.org/releases/$REPO_BRANCH/targets/x86/generic/openwrt-sdk-$REPO_BRANCH-x86-generic_gcc-13.3.0_musl.Linux-x86_64.tar.zst
-        elif [[ ${{matrix.target}} == "aarch64_generic" ]]; then
-            curl -fL -o sdk.tar.zst https://downloads.openwrt.org/releases/$REPO_BRANCH/targets/rockchip/armv8/openwrt-sdk-$REPO_BRANCH-rockchip-armv8_gcc-13.3.0_musl.Linux-x86_64.tar.zst
-        elif [[ ${{matrix.target}} == "arm_arm1176jzf-s_vfp" ]]; then
-            curl -fL -o sdk.tar.zst https://downloads.openwrt.org/releases/$REPO_BRANCH/targets/bcm27xx/bcm2708/openwrt-sdk-$REPO_BRANCH-bcm27xx-bcm2708_gcc-13.3.0_musl_eabi.Linux-x86_64.tar.zst
-        elif [[ ${{matrix.target}} == "arm_cortex-a15_neon-vfpv4" ]]; then
-            curl -fL -o sdk.tar.zst https://downloads.openwrt.org/releases/$REPO_BRANCH/targets/ipq806x/generic/openwrt-sdk-$REPO_BRANCH-ipq806x-generic_gcc-13.3.0_musl_eabi.Linux-x86_64.tar.zst
-        elif [[ ${{matrix.target}} == "arm_cortex-a5_vfpv4" ]]; then
-            curl -fL -o sdk.tar.zst https://downloads.openwrt.org/releases/$REPO_BRANCH/targets/at91/sama5/openwrt-sdk-$REPO_BRANCH-at91-sama5_gcc-13.3.0_musl_eabi.Linux-x86_64.tar.zst
-        elif [[ ${{matrix.target}} == "aarch64_cortex-a72" ]]; then
-            curl -fL -o sdk.tar.zst https://downloads.openwrt.org/releases/$REPO_BRANCH/targets/bcm27xx/bcm2711/openwrt-sdk-$REPO_BRANCH-bcm27xx-bcm2711_gcc-13.3.0_musl.Linux-x86_64.tar.zst
-        elif [[ ${{matrix.target}} == "aarch64_cortex-a53" ]]; then
-            curl -fL -o sdk.tar.zst https://downloads.openwrt.org/releases/$REPO_BRANCH/targets/mediatek/filogic/openwrt-sdk-$REPO_BRANCH-mediatek-filogic_gcc-13.3.0_musl.Linux-x86_64.tar.zst
-        elif [[ ${{matrix.target}} == "arm_cortex-a7_neon-vfpv4" ]]; then
-            curl -fL -o sdk.tar.zst https://downloads.openwrt.org/releases/$REPO_BRANCH/targets/ipq40xx/generic/openwrt-sdk-$REPO_BRANCH-ipq40xx-generic_gcc-13.3.0_musl_eabi.Linux-x86_64.tar.zst
-        elif [[ ${{matrix.target}} == "arm_cortex-a9" ]]; then
-            curl -fL -o sdk.tar.zst https://downloads.openwrt.org/releases/$REPO_BRANCH/targets/bcm53xx/generic/openwrt-sdk-$REPO_BRANCH-bcm53xx-generic_gcc-13.3.0_musl_eabi.Linux-x86_64.tar.zst
-        elif [[ ${{matrix.target}} == "arm_cortex-a9_vfpv3-d16" ]]; then
-            curl -fL -o sdk.tar.zst https://downloads.openwrt.org/releases/$REPO_BRANCH/targets/mvebu/cortexa9/openwrt-sdk-$REPO_BRANCH-mvebu-cortexa9_gcc-13.3.0_musl_eabi.Linux-x86_64.tar.zst
-        elif [[ ${{matrix.target}} == "aarch64_cortex-a76" ]]; then
-            curl -fL -o sdk.tar.zst https://downloads.openwrt.org/releases/$REPO_BRANCH/targets/bcm27xx/bcm2712/openwrt-sdk-$REPO_BRANCH-bcm27xx-bcm2712_gcc-13.3.0_musl.Linux-x86_64.tar.zst
+        if [[ "${{matrix.target}}" == "mipsel_24kc" ]]; then
+        	SDK_PATH="releases/$REPO_BRANCH/targets/ramips/mt7621/openwrt-sdk-$REPO_BRANCH-ramips-mt7621_gcc-14.3.0_musl.Linux-x86_64.tar.zst"
+        elif [[ "${{matrix.target}}" == "mips_24kc" ]]; then
+        	SDK_PATH="releases/$REPO_BRANCH/targets/ath79/nand/openwrt-sdk-$REPO_BRANCH-ath79-nand_gcc-14.3.0_musl.Linux-x86_64.tar.zst"
+        elif [[ "${{matrix.target}}" == "x86_64" ]]; then
+        	SDK_PATH="releases/$REPO_BRANCH/targets/x86/64/openwrt-sdk-$REPO_BRANCH-x86-64_gcc-14.3.0_musl.Linux-x86_64.tar.zst"
+        elif [[ "${{matrix.target}}" == "i386_pentium4" ]]; then
+        	SDK_PATH="releases/$REPO_BRANCH/targets/x86/generic/openwrt-sdk-$REPO_BRANCH-x86-generic_gcc-14.3.0_musl.Linux-x86_64.tar.zst"
+        elif [[ "${{matrix.target}}" == "aarch64_generic" ]]; then
+        	SDK_PATH="releases/$REPO_BRANCH/targets/rockchip/armv8/openwrt-sdk-$REPO_BRANCH-rockchip-armv8_gcc-14.3.0_musl.Linux-x86_64.tar.zst"
+        elif [[ "${{matrix.target}}" == "arm_arm1176jzf-s_vfp" ]]; then
+        	SDK_PATH="releases/$REPO_BRANCH/targets/bcm27xx/bcm2708/openwrt-sdk-$REPO_BRANCH-bcm27xx-bcm2708_gcc-14.3.0_musl_eabi.Linux-x86_64.tar.zst"
+        elif [[ "${{matrix.target}}" == "arm_cortex-a15_neon-vfpv4" ]]; then
+        	SDK_PATH="releases/$REPO_BRANCH/targets/ipq806x/generic/openwrt-sdk-$REPO_BRANCH-ipq806x-generic_gcc-14.3.0_musl_eabi.Linux-x86_64.tar.zst"
+        elif [[ "${{matrix.target}}" == "arm_cortex-a5_vfpv4" ]]; then
+        	SDK_PATH="releases/$REPO_BRANCH/targets/at91/sama5/openwrt-sdk-$REPO_BRANCH-at91-sama5_gcc-14.3.0_musl_eabi.Linux-x86_64.tar.zst"
+        elif [[ "${{matrix.target}}" == "aarch64_cortex-a72" ]]; then
+        	SDK_PATH="releases/$REPO_BRANCH/targets/bcm27xx/bcm2711/openwrt-sdk-$REPO_BRANCH-bcm27xx-bcm2711_gcc-14.3.0_musl.Linux-x86_64.tar.zst"
+        elif [[ "${{matrix.target}}" == "aarch64_cortex-a53" ]]; then
+        	SDK_PATH="releases/$REPO_BRANCH/targets/mediatek/filogic/openwrt-sdk-$REPO_BRANCH-mediatek-filogic_gcc-14.3.0_musl.Linux-x86_64.tar.zst"
+        elif [[ "${{matrix.target}}" == "arm_cortex-a7_neon-vfpv4" ]]; then
+        	SDK_PATH="releases/$REPO_BRANCH/targets/ipq40xx/generic/openwrt-sdk-$REPO_BRANCH-ipq40xx-generic_gcc-14.3.0_musl_eabi.Linux-x86_64.tar.zst"
+        elif [[ "${{matrix.target}}" == "arm_cortex-a9" ]]; then
+        	SDK_PATH="releases/$REPO_BRANCH/targets/bcm53xx/generic/openwrt-sdk-$REPO_BRANCH-bcm53xx-generic_gcc-14.3.0_musl_eabi.Linux-x86_64.tar.zst"
+        elif [[ "${{matrix.target}}" == "arm_cortex-a9_vfpv3-d16" ]]; then
+        	SDK_PATH="releases/$REPO_BRANCH/targets/mvebu/cortexa9/openwrt-sdk-$REPO_BRANCH-mvebu-cortexa9_gcc-14.3.0_musl_eabi.Linux-x86_64.tar.zst"
+        elif [[ "${{matrix.target}}" == "aarch64_cortex-a76" ]]; then
+        	SDK_PATH="releases/$REPO_BRANCH/targets/bcm27xx/bcm2712/openwrt-sdk-$REPO_BRANCH-bcm27xx-bcm2712_gcc-14.3.0_musl.Linux-x86_64.tar.zst"
+        elif [[ "${{matrix.target}}" == "riscv64_generic" ]]; then
+        	SDK_PATH="releases/$REPO_BRANCH/targets/bcm27xx/bcm2712/openwrt-sdk-$REPO_BRANCH-siflower-sf21_gcc-14.3.0_musl.Linux-x86_64.tar.zst"
         fi
+
+        PRIMARY_URL="https://downloads.openwrt.org/$SDK_PATH"
+        MIRROR_URL="https://mirror-03.infra.openwrt.org/$SDK_PATH"
+
+        wget -c -O sdk.tar.zst "$PRIMARY_URL" || {
+        	echo "Primary download failed, trying mirror..."
+        	wget -c -O sdk.tar.zst "$MIRROR_URL"
+        }
+
 
     - name: Free up disk space
       env:
         DEBIAN_FRONTEND: noninteractive
       run: |
         sudo mkdir -p -m 777 openwrt /mnt/openwrt/staging_dir /mnt/openwrt/build_dir /mnt/openwrt/bin  /mnt/openwrt/dl
-        if [[ "$(echo "${{github.event.action}}" | grep "a-")" ]]; then
-          ln -sf /mnt/openwrt/staging_dir openwrt/staging_dir
-          ln -sf /mnt/openwrt/bin openwrt/bin
-          ln -sf /mnt/openwrt/dl openwrt/dl
           ln -sf /mnt/openwrt/build_dir openwrt/build_dir
-        fi
+          ln -sf /mnt/openwrt/staging_dir openwrt/staging_dir
         df -hT
     
     - name: Load custom configuration
@@ -172,11 +180,11 @@ jobs:
           }
         export -f git_clone_path
         tar -xJf sdk.tar.zst -C openwrt || tar -xf sdk.tar.zst -C openwrt
-        rm -Rf sdk.tar.zst
         cd openwrt
         cp -rf ./openwrt-sdk*/. ./ 2>/dev/null || true
         cp -rf ./openwrt-sdk*/build_dir/. ./build_dir/ || true
         cp -rf ./openwrt-sdk*/staging_dir/. ./staging_dir/ || true
+        rm -rf openwrt-sdk* ../sdk.tar.zst
         cp -rf ../devices ./
         cp -rf devices/common/. ./
         cp -rf devices/${{matrix.target}}/. ./
@@ -193,10 +201,7 @@ jobs:
           find "devices/${{matrix.target}}/patches" -type f -name '*.patch' -print0 | sort -z | xargs -I % -t -0 -n 1 sh -c "cat '%'  | patch -d './' -p1 -E --forward --no-backup-if-mismatch"
         fi
         cp -Rf ./diy/* ./ || true
-        if [ -f "devices/${{matrix.target}}/default-settings" ]; then
-          echo >> package/*/*/my-default-settings/files/etc/uci-defaults/99-default-settings
-          cat devices/${{matrix.target}}/default-settings >> package/*/*/my-default-settings/files/etc/uci-defaults/99-default-settings
-        fi
+        sed -i 's/--set=llvm\.download-ci-llvm=true/--set=llvm.download-ci-llvm=false/' feeds/packages/lang/rust/Makefile
         if [ -f "devices/${{matrix.target}}/.config" ]; then
           echo >> .config
           cat devices/${{matrix.target}}/.config >> .config
@@ -224,7 +229,7 @@ jobs:
       run: |
         cd openwrt
           echo -e "$(($(nproc)+1)) thread compile"
-          fpkg="$(echo "${{github.event.action}}" | sed -e 's/\(aarch64_generic\|x86_64\|i386_pentium4\|arm_arm1176jzf-s_vfp\|aarch64_cortex-a72\|aarch64_cortex-a76\|arm_cortex-a7\|arm_cortex-a7_neon-vfpv4\|arm_cortex-a9\|arm_cortex-a15_neon-vfpv4\|arm_cortex-a5_vfpv4\|mipsel_24kc\|mips_24kc\|aarch64_cortex-a53\|arm_xscale\|arm_cortex-a9_vfpv3-d16\| [0-9][0-9.]*\| ssh\| noser\| cw\)//g' | sed -e 's/ //g')"
+          fpkg="$(echo "${{github.event.action}}" | sed -e 's/\(aarch64_generic\|x86_64\|i386_pentium4\|arm_arm1176jzf-s_vfp\|aarch64_cortex-a72\|aarch64_cortex-a76\|arm_cortex-a7\|arm_cortex-a7_neon-vfpv4\|arm_cortex-a9\|arm_cortex-a15_neon-vfpv4\|arm_cortex-a5_vfpv4\|mipsel_24kc\|mips_24kc\|aarch64_cortex-a53\|arm_xscale\|arm_cortex-a9_vfpv3-d16\|riscv64_generic\| [0-9][0-9.]*\| ssh\| noser\| cw\)//g' | sed -e 's/ //g')"
           echo "FPKG=$fpkg" >> $GITHUB_ENV
           during="$(echo "${{github.event.action}}" | grep -o -E ' [0-9][0-9.]*' | sed -e 's/ //')"
           function comp(){
@@ -352,7 +357,7 @@ jobs:
         REMOTE_HOST: ${{ secrets.SERVER_HOST }}
         REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
         REMOTE_PORT: ${{ secrets.SERVER_PORT }}
-        TARGET: "/www/wwwroot/dl.openwrt.ai/releases/24.10/packages/${{matrix.target}}/kiddin9/"
+        TARGET: "/www/wwwroot/dl.openwrt.ai/releases/25.12/packages/${{matrix.target}}/kiddin9/"
         SCRIPT_AFTER: |
             bash opkg ${{matrix.target}} &
 
