Update Packages-AutoBuild.yml

diff --git a/.github/workflows/Packages-AutoBuild.yml b/.github/workflows/Packages-AutoBuild.yml
--- a/.github/workflows/Packages-AutoBuild.yml
+++ b/.github/workflows/Packages-AutoBuild.yml
@@ -232,7 +232,7 @@ jobs:
              echo "compile $ipk"
              cp -rf kiddin9.b/$ipk* package/feeds/kiddin9/
              [ "$(grep "PKG_BUILD_DEPENDS" package/feeds/kiddin9/$ipk/Makefile)" ] && mv -f feeds/packages/lang/node.b feeds/packages/lang/node 2>/dev/null || mv feeds/packages/lang/node feeds/packages/lang/node.b 2>/dev/null || true
-             make -k package/$ipk/compile -j$(($(nproc)+1)) || (make -k package/$ipk/compile V=s 2>&1 | tee error_$ipk.log | grep -i "Error 2" || true &)
+             make -k package/$ipk/compile -j$(($(nproc)+1)) || (make -k package/$ipk/compile V=s 2>&1 | tee error_$ipk.log | grep -i "Error 2" || true)
              rm -rf package/feeds/kiddin9/$ipk*
             }
           for ipk in $(ls kiddin9.b | grep -E "$fpkg"); do
@@ -269,7 +269,6 @@ jobs:
                 comp
               done
           fi
-          wait
         echo "status=success" >> $GITHUB_ENV
 
     - name: Check space usage
